apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretly
  namespace: default
  labels:
    app: secretly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretly
  template:
    metadata:
      labels:
        app: secretly
    spec:
      containers:
        - name: secretly
          image: localhost:5000/secretly:latest
          command: ["./secretly"]
          args: ["replicate"]
      serviceAccountName: secretly
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretly
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretly
subjects:
- kind: ServiceAccount
  name: secretly
  namespace: default
roleRef:
  kind: ClusterRole
  name: secretly
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretly
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create"]
